networks:
  project:
    driver: bridge
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - project
  frontend:
    container_name: frontend
    image: ghcr.io/seaz96/alpha-students-projects-frontend:main
    volumes:
      - ./src:/app/src
    ports:
      - "80"
    networks:
      - project
  backend:
    container_name: server
    image: ghcr.io/seaz96/alpha-students-projects-backend:main
    ports:
      - "8080:8080"
    networks:
      - project
    depends_on:
      - db
    environment:
      DATABASE_HOST: postgres_db
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      SECURITY_KEY: DefaultDevelopmentSecurityKey0123456789,
      DOCUMENTATION_SERVER: http://localhost:8080/api
      S3_PROTOCOL: https
      S3_HOST: files.student-projects.ru
      S3_PUBLIC_KEY: admin
      S3_SECRET_KEY: gans41og
      CORS_ORIGINS: https://student-projects.ru
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    expose:
      - '9000' 
      - '9001'
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - project
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=gans41og
      - MINIO_DEFAULT_BUCKETS=teams
  db:
    container_name: postgres_db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - project
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  caddy_data:
  caddy_config:
  db-data:
  minio-data:
